# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-03 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_name', models.CharField(max_length=50)),
                ('exercise_desc', models.CharField(max_length=50)),
                ('exercise_reps', models.IntegerField()),
                ('exercise_duration', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Exercise',
                'db_table': '',
                'managed': True,
                'verbose_name_plural': 'Exercises',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercises', models.CharField(max_length=50)),
                ('available_skips', models.IntegerField()),
                ('muscle_group', models.CharField(max_length=50)),
                ('total_time', models.IntegerField()),
                ('motivation_img_url', models.URLField()),
            ],
            options={
                'verbose_name': 'Workout',
                'db_table': '',
                'managed': True,
                'verbose_name_plural': 'Workouts',
            },
        ),
    ]
