# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-03 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_trainer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='workout_name',
            field=models.CharField(default='My first workout', max_length=50),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='exercise_name',
            field=models.CharField(default='My first exercise', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='Me', max_length=50),
        ),
    ]
