# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-03 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_trainer', '0002_auto_20200103_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='exercise_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='workout',
            name='workout_name',
            field=models.CharField(max_length=50),
        ),
    ]
